---
- name: To install httpd
  hosts: all
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

- name: to start service
  hosts: all
  become: true
  tasks:
  - name: start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

- name: to install apache2
  hosts: all
  become: true
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

- name: to start service
  hosts: all
  become: true
  tasks:
  - name: start apache2 service
    service:
      name: apache2
      state: started
    when:  ansible_os_family == "Debian"

- name: copy index.html file
  hosts: all
  become: true
  tasks:
  - name: copy index file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0666

