---
- name: installing httpd
  hosts: webservers
  become: true
  tasks:
  - name: install a httpd pkg
    yum:
      name: httpd
      state: latest
    notify: start httpd

  handlers:
  - name:  start httpd
    service:
      name: httpd
      state: started
