---
- name: installing hhtpd
  hosts: all
  become: true
  tasks:
  - name: install a httpd package
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: htt
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: install apache2
    apt:
      name: apache2
      state: latest
    when: ansible_os_family == "Debian"

  - name: start service apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0777

