---
- name: uninstall httpd
  hosts: all
  become: true
  tasks:

  - name: service stopping httpd
    service:
      name: httpd
      state: stopped

  - name: uninstalling httpd
    yum:
      name: httpd
      state: removed
